### ISSUE TITLE
Add API docs

### ISSUE THREAD

**Issue by nreinicke** [NREL/routee-powertrain#2]
Using sphinx and autodoc, we should add an API docs page to the documentation. Here's an example configuration for the jupyter-book config file:

```yaml
sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.viewcode"
  config:
    html_theme: sphinx_book_theme
    language: "python"
  html_context:
    default_mode: light

  # Autodoc config reference
  # https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#configuration
  autodoc_default_options:
    members: true
    member-order: bysource
    private-members: true
```
